In [69]:
import pandas as pd
import numpy as np
import os
from binascii import hexlify,unhexlify
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
sns.set(rc={'figure.figsize':(11.7,8.27)})

mms = MinMaxScaler()

In [70]:
folders  = os.listdir('results')
data     = list(map(lambda x:x.split('.')[0],folders))
data     = list(map(lambda x: x.encode('utf-8'),data))
data     = list(map(lambda x: unhexlify(x),data))
data     = list(map(lambda x: str(x,'ascii'),data))
data     = list(map(lambda x: x.split(':'),data))
def toFloat2(x):
    fx = float
    return (list(map(fx,x[0])),list(map(fx,x[1]) ))
cols = ["SAMPLES","SIZE","INTER_ARRIVAL","READ_RATIO","SAS_SIZE","DISTRIBUTION","MEAN","STD","CONCURRENCY","AVG_IA","AVG_ST","DELAYS"]
df       = pd.DataFrame(data,columns=cols) 
data     = list(map(lambda x: (x[:9],x[9:]),data))
data     = list(map(toFloat2,data))
x = list(zip(data,folders))
y = list(map(lambda x: open("./results/"+x,'r'),folders))
y = list(map(lambda x: x.readlines(),y))
# len(y)

In [71]:
def getQueueInf(x):
    x0 = list(map(lambda y:y.strip(),x))
    
    x1 = x0[-1]
    x2 = x1.split(',')
    # Bad solution,ik, butno time :c.
    x3 = list(map(lambda x: 0.0 if x =='r' else float(x),x2))
    return x2
w = y
# print(len(y))
z = list(map (getQueueInf,w) )
# print(len(z))
values =df.to_numpy().tolist()

values[0]+z[0]
v =list(zip(z,values))
v = list(map( lambda x:x[0]+x[1],v))
cols2 = ["AVG_DIQ","NIQ","SERVER_UTILIZATION","SIMULATION_TIME"]+cols
df2 = pd.DataFrame(v,columns=cols2)
df2 = df2.apply(pd.to_numeric)
df2

,AVG_DIQ,NIQ,SERVER_UTILIZATION,SIMULATION_TIME,SAMPLES,SIZE,INTER_ARRIVAL,READ_RATIO,SAS_SIZE,DISTRIBUTION,MEAN,STD,CONCURRENCY,AVG_IA,AVG_ST,DELAYS
0,1.812563e+06,16.770859,0.995415,1.270588e+07,100,500,100,80,549093,2,0,0,1,133384.608247,135000,100
1,8.238413e+00,0.005787,0.070309,1.423681e+07,10000,500,1,80,549093,3,10,5,1,1426.319459,100,10000
2,3.585994e+03,0.666215,0.573559,5.382636e+06,1000,500,10,80,549093,3,10,5,1,5609.030039,3100,1000
3,1.690141e+01,0.012445,0.109995,1.358100e+06,1000,500,1,80,549093,3,10,5,1,1416.777454,150,1000
4,0.000000e+00,0.000000,0.000000,3.735081e+05,1000,500,1,80,549093,1,0,0,1,1541.827375,2100,1000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,4.889690e+04,0.360292,0.442533,1.357147e+09,10000,500,100,80,549093,2,0,0,1,135959.705480,60000,10000
266,8.734763e+03,1.081595,0.696050,8.075812e+05,100,500,10,80,549093,2,0,0,1,10595.845361,6000,100
267,1.801666e+00,0.000313,0.017408,5.749804e+07,10000,500,10,80,549093,3,10,5,1,5760.450591,100,10000
268,2.153428e+02,0.035481,0.164927,6.069204e+07,10000,500,10,80,549093,1,0,0,1,6080.425350,1000,10000
269,6.904006e+03,1.170165,0.675123,5.900487e+06,1000,500,10,80,549093,1,0,0,1,6144.936670,4000,1000

In [214]:
distribution = 2
distributions = ('Uniform','Poisson','Normal')
IA = 'INTER_ARRIVAL'
AIA = 'AVG_IA'
uniform = df2.loc[df2['DISTRIBUTION']==distribution]
uniform['AVG_ST'].loc[uniform['AVG_ST'].index] = uniform['AVG_ST']/1000
uniform[IA].loc[uniform[IA].index] = uniform[IA]/1000
uniform[AIA].loc[uniform[AIA].index] = uniform[AIA]/1000
d2 = d
d2 = d2.drop(d[d[SU]==0].index)
d2.head(10)
# d = uniform[[SU,'AVG_ST','INTER_ARRIVAL','AVG_IA']].sort_values(SU,ascending=False)
# d
# d2 = d[d[IA]==0.001]
# ax = d2.plot(y=SU,x=AIA,kind='bar')
# ax.set_title("{} distribution".format(distributions[distribution-1]))
# ax.set_xlabel("AVARAGE INTERARRIVAL(seconds)")
# ax.set_ylabel("SERVER UTILIZATION")
# ax.xaxis.set_major_locator(ticker.MultipleLocator(2))
# ax.xaxis.set_major_formatter(ticker.ScalarFormatter())
# ax = sns.barplot(y=SU,x=AIA,data=d2)
# d.sort_values('AVG_ST')
# d[SU] = d[SU]*100
# d.plot(y=SU,x='INTER_ARRIVAL',kind='bar')
# ax = sns.scatterplot(y=SU,x=ST,data=d)
# ax.set_xlabel("SERVICE TIME")
# ax.set_title("{} distribution".format(distributions[distribution-1]))
# d.sort_values(IA)

/home/nacho/.local/lib/python3.8/site-packages/pandas/core/indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
<ipython-input-214-a5a0189787aa>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  uniform['AVG_ST'].loc[uniform['AVG_ST'].index] = uniform['AVG_ST']/1000
<ipython-input-214-a5a0189787aa>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  uniform[IA].loc[uniform[IA].index] = uniform[IA]/1000
<ipython-input-214-a5a0189787aa>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  uniform[AIA].loc[uniform[AIA].index] = uniform[AIA]/1000

     SERVER_UTILIZATION  AVG_ST  INTER_ARRIVAL    AVG_IA
110            0.999435     1.5          0.001  1.514639
101            0.997877     2.5          0.001  1.519794
75             0.997696     2.2          0.001  1.451959
17             0.997512     2.1          0.001  1.497165
129            0.997429     2.0          0.001  1.473186
239            0.994027     1.5          0.001  1.514660
164            0.980015     1.5          0.001  1.528754
263            0.956235     1.2          0.001  1.542557
172            0.899785     1.1          0.001  1.502722
227            0.871563     4.5          0.010  6.346557

In [72]:
SU ='SERVER_UTILIZATION'
ST ="AVG_ST"
D  = 'DISTRIBUTION'
def getByDistribution(distribution,**kwargs):
    dff =kwargs.get('df',df2)
    dff = dff.loc[dff[D]==distribution]
    dff = dff.drop(dff[dff['NIQ'] =='r'].index)
    dff = dff.apply(pd.to_numeric)
    return dff
uniform = getByDistribution(1)
# uniform.loc[ uniform[SU]==0.0]
uniform = uniform.sort_values(SU)
# uniform.plot(y=SU,x=)
dsu  = uniform.loc[uniform[SU]>0]
dsu  = dsu[['AVG_DIQ',SU,'NIQ','SIMULATION_TIME','INTER_ARRIVAL','DISTRIBUTION','AVG_IA','AVG_ST']]
dsu.sort_values('AVG_DIQ')

,AVG_DIQ,SERVER_UTILIZATION,NIQ,SIMULATION_TIME,INTER_ARRIVAL,DISTRIBUTION,AVG_IA,AVG_ST
73,0.000000,0.002535,0.000000,3.695018e+06,100,1,48480.371134,100
138,0.095000,0.001928,0.000002,5.181869e+08,100,1,51914.673742,100
252,0.166000,0.002000,0.000003,4.979099e+07,100,1,51944.924413,100
88,1.682480,0.016316,0.000274,6.134740e+07,10,1,6146.102868,100
147,2.409863,0.016903,0.000409,5.891852e+06,10,1,6146.735444,100
...,...,...,...,...,...,...,...,...
129,45505.000000,0.997429,36.628078,1.878551e+05,1,1,1473.185567,2000
17,49642.734375,0.997512,39.068951,1.972316e+05,1,1,1497.164948,2100
164,53997.093750,0.980015,35.313789,1.532080e+07,1,1,1528.754159,1500
75,56374.101562,0.997696,45.075924,2.065854e+05,1,1,1451.958763,2200
101,68941.000000,0.997877,51.973137,2.347134e+05,1,1,1519.793814,2500

In [111]:
SIT = "SIMULATION_TIME"
d   = dsu[[SU,'AVG_ST']]
d   = d.sort_values(SU)
d
# ax   = sns.barplot(y=SU,x='AVG_ST',data=dsu)
# ax =sns.barplot(y=SU,x='NIQ',data=uniform)
# ax.xaxis.set_major_locator(ticker.MultipleLocator(5))
# ax.xaxis.set_major_formatter(ticker.ScalarFormatter())

     SERVER_UTILIZATION  AVG_ST
138            0.001928     100
252            0.002000     100
73             0.002535     100
26             0.009694     500
38             0.009892     500
..                  ...     ...
129            0.997429    2000
17             0.997512    2100
75             0.997696    2200
101            0.997877    2500
110            0.999435    1500

[79 rows x 2 columns]